name: Build

on:
  push:
    branches:
      - "gh-pages"
      - master
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present


      - name: Publish release
        run: git push origin "gh-pages"

  prevent_failed_status:
    name: Prevent failed status when skipped
    runs-on: ubuntu-latest
    steps:
      - name: Prevent failed status when skipped
        run: |
          echo "Run this job to prevent the workflow status from showing as" \
               "failed when all other jobs are skipped ok."


      #- name: Deploy
     #   uses: ./
      #    with:
       #     publish_branch: "gh-pages"  # default: gh-pages github_token: ${{ secrets.GITHUB_TOKEN }}


