name: Node.js Package

on:
  release:  ## push?
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm build
      - run: npm test
      echo 'build npm'

    deploy:
      provider: pages
      local_dir: dist
      ob:
        branch: "gh-pages"


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
       # env:
        #  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        echo 'pub npm'
